defaults:
  - base_config
  - override data: base
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./output/${exp_id}
  output_subdir: train-${now:%Y-%m-%d_%H-%M-%S}-hydra

ema: 
  start: 0

mini_train: False
example_train: False
enable_grad_scaler: False
vgg_oversample_rate: 5

log_text_interval: 200
log_extra_interval: 20_000
val_interval: 5_000
eval_interval: 20_000
save_eval_interval: 40_000
save_weights_interval: 10_000
save_checkpoint_interval: 10_000
save_copy_iterations: []

batch_size: 512
eval_batch_size: 256 # per-GPU

num_iterations: 300_000
learning_rate: 1.0e-4
linear_warmup_steps: 1_000

lr_schedule: step
lr_schedule_steps: [240_000, 270_000]
lr_schedule_gamma: 0.1

clip_grad_norm: 1.0
weight_decay: 1.0e-6
